services:
  audiobookshelf_custom:
    image: audiobookshelf_custom
    container_name: audiobookshelf_custom
    platform: linux/amd64
    build:
      context: .
      args:
        - TARGETPLATFORM=linux/amd64
    ports:
      - 3042:80
    volumes:
      - /home/chris/audiobookshelf/audiobooks:/audiobooks
      - /home/chris/audiobookshelf/podcasts:/podcasts
      - /home/chris/audiobookshelf/metadata:/metadata
      - /home/chris/audiobookshelf/config:/config
    environment:
      - TZ=Asia/Taipei
      - ROUTER_BASE_PATH=/ai
    restart: always
